import type { Metadata } from "next";
import "./globals.css";

import { headers } from 'next/headers'
import { cookieToInitialState } from 'wagmi'

import { Providers } from "./Providers/providers";

import {config} from '../config'


export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  const initialState = cookieToInitialState(
    config,
    headers().get('cookie')
  )
  return (
    <html lang="en">
      <body 
        className='antialiased'
      >
        <Providers initialState={initialState}>
          {children}
        </Providers>
      </body>
    </html>
  );
}
